package com.bwie.zhouxinguang124;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwie.zhouxinguang124.bean.Stdudent;

import com.bwie.zhouxinguang124.StdudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stdudentDaoConfig;

    private final StdudentDao stdudentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stdudentDaoConfig = daoConfigMap.get(StdudentDao.class).clone();
        stdudentDaoConfig.initIdentityScope(type);

        stdudentDao = new StdudentDao(stdudentDaoConfig, this);

        registerDao(Stdudent.class, stdudentDao);
    }
    
    public void clear() {
        stdudentDaoConfig.clearIdentityScope();
    }

    public StdudentDao getStdudentDao() {
        return stdudentDao;
    }

}
